

# Generated by Django 5.2 on 2025-05-04 20:09



from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_booked_for',
        ),
    ]
