# Generated by Django 5.2 on 2025-05-08 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
        migrations.AlterModelOptions(
            name="emailnotificationpreference",
            options={"verbose_name_plural": "Email Notification Preferences"},
        ),
        migrations.AlterModelOptions(
            name="userskill",
            options={"ordering": ["user", "skill__name"]},
        ),
        migrations.AlterField(
            model_name="userskill",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="userskill",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="userskill",
            name="skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_skills",
                to="skills.skill",
            ),
        ),
    ]
