<<<<<<< HEAD
# Generated by Django 5.2 on 2025-05-05 09:17
=======
# Generated by Django 5.2 on 2025-05-04 20:09
>>>>>>> 7139178dae86b4d0f389f63f418fefdb4fa928e5

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_booked_for',
        ),
    ]
