# Generated by Django 5.2 on 2025-05-08 19:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "authentication",
            "0002_remove_user_groups_remove_user_user_permissions_and_more",
        ),
        ("skills", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="userskill",
            index=models.Index(
                fields=["user", "skill"], name="authenticat_user_id_a5aa81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userskill",
            index=models.Index(fields=["skill"], name="authenticat_skill_i_f135fb_idx"),
        ),
        migrations.AddIndex(
            model_name="userskill",
            index=models.Index(fields=["user"], name="authenticat_user_id_970450_idx"),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
