# Generated by Django 5.2 on 2025-05-04 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_emailnotificationpreference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailnotificationpreference',
            old_name='job_alerts',
            new_name='skill_match_alerts',
        ),
    ]
