# Generated by Django 5.2 on 2025-05-04 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_job_alerts_emailnotificationpreference_skill_match_alerts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_provider',
        ),
    ]
