# Generated by Django 5.2 on 2025-05-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userskill_address_userskill_location_userskill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskill',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
