# Generated by Django 5.2 on 2025-05-08 20:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_userskill_authenticat_user_id_a5aa81_idx_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserSkill",
        ),
    ]
