# Generated by Django 5.2 on 2025-05-08 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skills", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="endorsements",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="skill",
            name="experience_hours",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="skill",
            name="level",
            field=models.CharField(
                choices=[
                    ("Beginner", "Beginner"),
                    ("Intermediate", "Intermediate"),
                    ("Expert", "Expert"),
                ],
                default="Beginner",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(fields=["name"], name="skills_skil_name_c82d47_idx"),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(fields=["user"], name="skills_skil_user_id_d04977_idx"),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["is_offered"], name="skills_skil_is_offe_320fb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["is_visible"], name="skills_skil_is_visi_b2dad3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["location"], name="skills_skil_locatio_a3c1ea_idx"
            ),
        ),
    ]
