# Generated by Django 5.2.1 on 2025-05-11 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_tag_alter_availabilityslot_options_and_more'),
        ('skills', '0002_skill_endorsements_skill_experience_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('user', 'name')},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='tags',
        ),
        migrations.AddField(
            model_name='skill',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='skills', to='bookings.tag'),
        ),
    ]
