# Generated by Django 5.2 on 2025-04-30 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_servicerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='serviceoffering',
            unique_together={('user', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='servicerequest',
            unique_together={('user', 'title')},
        ),
    ]
