# Generated by Django 5.2 on 2025-04-30 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_servicerequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='service_offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skills.serviceoffering'),
        ),
    ]
