# Generated by Django 5.2 on 2025-05-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_servicerequest_service_offering'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='mode',
            field=models.CharField(choices=[('remote', 'Remote'), ('local', 'Local')], default='remote', max_length=10),
        ),
    ]
