# Generated by Django 5.2 on 2025-05-03 18:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_skill_address_skill_city_skill_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='service_offering',
        ),
        migrations.AlterUniqueTogether(
            name='servicerequest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='city',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='mode',
        ),
        migrations.AddField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_offered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='location',
            field=models.CharField(choices=[('local', 'Local'), ('remote', 'Remote')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='skill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='ServiceOffering',
        ),
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
    ]
