# Generated by Django 5.2 on 2025-05-03 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmembership',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='groupmembership',
            name='status',
        ),
    ]
