# Generated by Django 5.2 on 2025-05-08 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="groupannouncement",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="groupmembership",
            options={"ordering": ["joined_at"]},
        ),
        migrations.AddField(
            model_name="group",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="group_images/"),
        ),
        migrations.AddField(
            model_name="group",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="groupannouncement",
            name="posted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posted_announcements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userstats",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_stats",
                to="groups.group",
            ),
        ),
        migrations.AlterField(
            model_name="userstats",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_stats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userstats",
            unique_together={("user", "group")},
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(fields=["owner"], name="groups_grou_owner_i_11ab1b_idx"),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(
                fields=["is_active"], name="groups_grou_is_acti_044fa7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupannouncement",
            index=models.Index(
                fields=["group", "-created_at"], name="groups_grou_group_i_ea819d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupmembership",
            index=models.Index(
                fields=["group", "is_active"], name="groups_grou_group_i_f7e3a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userstats",
            index=models.Index(
                fields=["user", "group"], name="groups_user_user_id_448ece_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userstats",
            index=models.Index(fields=["group"], name="groups_user_group_i_d342f5_idx"),
        ),
    ]
