# Generated by Django 5.2 on 2025-05-02 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_wallet_balance'),
        ('wallet', '0003_remove_transaction_status_and_more'),
    ]

    operations = [
    ]
