# Generated by Django 5.2 on 2025-05-08 18:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leaderboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userstats",
            options={"verbose_name_plural": "User Stats"},
        ),
        migrations.AlterField(
            model_name="userstats",
            name="sessions_completed",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="userstats",
            name="total_hours_given",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="userstats",
            name="total_hours_received",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
