# Generated by Django 5.2 on 2025-05-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='total_hours_received',
            field=models.FloatField(default=0),
        ),
    ]
